server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://SkillSharingApplication:SkillSharingApplication@skillsharingapplication.jmrmquv.mongodb.net/skill-sharing-platform
  security:
    user:
      name: admin
      password: admin

app:
  jwt:
    secret: SkillSharingSecretKeyForJWTTokenGeneration12345
    expiration-ms: 3600000 # 1 hour in milliseconds